version: '3.3'

services:
  neo4j:
    image: neo4j:4.0
    ports:
      - 7474:7474 # for HTTP
      - 7473:7473 # for HTTPS
      - 7687:7687 # for Bolt
    volumes:
      - './data/neo4j:/data'
    environment:
      NEO4J_AUTH: "neo4j/password"
  corenlp:
    image: nlpbox/corenlp
    #command: /app/model/talbanken/run-server.sh
    #working_dir: /app
    #depends:
    #  - corenlp-train
    ports:
      - 9000:9000
    environment:
        JAVA_XMX: 16g
    volumes:
      - './models:/app/models'
      - './data:/app/data'
      - './run-server.sh:/app/model/talkbanken/run-server.sh'

  corenlp-train:
    image: nlpbox/corenlp
    command: /app/train.sh all /opt/corenlp
    working_dir: /app
    environment:
        JAVA_XMX: 16g
    volumes:
      - './models:/app/models'
      - './data:/app/data'

  minie:
    build: minie
    command: mvn clean compile assembly:assembly -DdescriptorId=jar-with-dependencies
    volumes:
      - minie:/opt/minie

  maltparser:
    build: maltparser
    volumes:
      - maltparser:/opt/maltparser

  information-extraction:
    build: .
    command: bash -c "python3 main.py matches --dataset data/movie_dataset/summary-en.csv --language eng"
    environment:
      CLASSPATH: /home/dev/minie/target/minie-0.0.1-SNAPSHOT.jar
    volumes:
      - /home/johlin/.history:/home/dev/.history
      - /home/johlin/.zsh_history:/home/dev/.zsh_history:rw
      - ./:/home/dev/workspace/stanford-corenlp
      - minie:/home/dev/workspace/minie
      - maltparser:/home/dev/workspace/maltparser
    depends_on:
      - corenlp
      - minie
      - maltparser

volumes:
  minie:
  maltparser: